=== simengy/FAE_Link_Analysis/schema/app_schema.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="app" type="vividApp" />

	<xs:element name="apps" type="vividApps" />

	<xs:element name="datasource" type="datasource" />

	<xs:element name="mail" type="mailConfig" />

	<xs:element name="property" type="property" />

	<xs:complexType name="vividApps">
		<xs:complexContent>
			<xs:extension base="abstractRequestBody">
				<xs:sequence>
					<xs:element ref="app" minOccurs="1" maxOccurs="1" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="abstractRequestBody" abstract="true">
		<xs:sequence />
	</xs:complexType>

	<xs:complexType name="vividApp">
		<xs:complexContent>
			<xs:extension base="abstractRequestBody">
				<xs:all>
					<xs:element name="datasources" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element ref="datasource" minOccurs="0" maxOccurs="unbounded" />
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="streams" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="stream" type="datasource" minOccurs="0" maxOccurs="unbounded" />
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="analysises" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="analysis" type="analysis"
									minOccurs="0" maxOccurs="unbounded" />
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="caches" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="cache" type="cache" minOccurs="0"
									maxOccurs="unbounded" />
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="exports" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="export" type="export" minOccurs="0"
									maxOccurs="unbounded" />
							</xs:sequence>
						</xs:complexType>
					</xs:element>
<!-- 					<xs:element name="ruleEngines" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="ruleEngine" type="ruleEngine"
									minOccurs="0" maxOccurs="unbounded" />
							</xs:sequence>
						</xs:complexType>
					</xs:element> -->
<!-- 					<xs:element name="messageSource" minOccurs="0">
						<xs:complexType>
							<xs:all>
								<xs:element name="files" maxOccurs="1" minOccurs="1">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="file" type="xs:string"
												minOccurs="0" maxOccurs="unbounded" />
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="langs" maxOccurs="1" minOccurs="1">
									<xs:complexType>
										<xs:sequence maxOccurs="1" minOccurs="1">
											<xs:element name="lang" type="lang" minOccurs="0"
												maxOccurs="unbounded" />
										</xs:sequence>
									</xs:complexType>
								</xs:element>
							</xs:all>
						</xs:complexType>
					</xs:element> -->
					<xs:element name="view" type="xs:string" minOccurs="1"
						maxOccurs="1" />
					<xs:element name="mailConfig" type="mailConfig"
						minOccurs="0" />
					<xs:element name="messaging" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="properties" minOccurs="0">
									<xs:complexType>
										<xs:sequence>
											<xs:element ref="property" minOccurs="0"
												maxOccurs="unbounded" />
										</xs:sequence>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
							<xs:attribute name="class" type="xs:string" use="required" />
						</xs:complexType>
					</xs:element>
					<xs:element name="userLog" type="userLog" minOccurs="0" />
				</xs:all>
				<xs:attribute name="enableCache" type="xs:boolean" use="optional"
					default="true" />
				<xs:attribute name="enableUiErrorMsgs" type="xs:boolean"
					use="optional" default="true" />
				<xs:attribute name="name" type="xs:string" use="required" />
				<xs:attribute name="root" type="xs:string" use="required" />
				<xs:attribute name="xmlRoot" type="xs:string" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="datasource">
		<xs:complexContent>
			<xs:extension base="abstractRequestBody">
				<xs:sequence>
					<xs:element name="properties" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element ref="property" minOccurs="0" maxOccurs="unbounded" />
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
				<xs:attribute name="class" type="xs:string" use="required" />
				<xs:attribute name="name" type="xs:string" use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="analysis">
		<xs:complexContent>
			<xs:extension base="abstractRequestBody">
				<xs:all>
					<xs:element name="properties" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element ref="property" minOccurs="0" maxOccurs="unbounded" />
							</xs:sequence>
						</xs:complexType>
					</xs:element>
<!-- 					<xs:element name="customTag" minOccurs="0" maxOccurs="1"></xs:element> -->
				</xs:all>
				<xs:attribute name="class" type="xs:string" use="required" />
				<xs:attribute name="name" type="xs:string" use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="export">
		<xs:complexContent>
			<xs:extension base="abstractRequestBody">
				<xs:sequence>
					<xs:element name="properties" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element ref="property" minOccurs="0" maxOccurs="unbounded" />
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
				<xs:attribute name="class" type="xs:string" use="required" />
				<xs:attribute name="name" type="xs:string" use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="cache">
		<xs:all>
			<xs:element name="properties" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element ref="property" minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="invalidator" type="invalidator"
				minOccurs="0"></xs:element>
		</xs:all>
		<xs:attribute name="class" type="xs:string" use="required" />
		<xs:attribute name="name" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="invalidator">
		<xs:complexContent>
			<xs:extension base="abstractRequestBody">
				<xs:sequence>
					<xs:element name="properties" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element ref="property" minOccurs="0" maxOccurs="unbounded" />
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
				<xs:attribute name="class" type="xs:string" use="required" />
				<xs:attribute name="name" type="xs:string" use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>


<!-- 	<xs:complexType name="customTag">
				<xs:attribute name="class" type="xs:string" use="required" />
				<xs:attribute name="xsdLocation" type="xs:string" use="optional" />
	</xs:complexType>
 -->

	<!-- <xs:complexType name="ruleEngine">
		<xs:complexContent>
			<xs:extension base="abstractRequestBody">
				<xs:sequence>
					<xs:element name="properties" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element ref="property" minOccurs="0" maxOccurs="unbounded" />
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
				<xs:attribute name="class" type="xs:string" use="required" />
				<xs:attribute name="name" type="xs:string" use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType> -->

	<xs:complexType name="property">
		<xs:complexContent>
			<xs:extension base="abstractRequestBody">
				<xs:sequence />
				<xs:attribute name="key" type="xs:string" use="required" />
				<xs:attribute name="value" type="xs:string" use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="mailConfig">
		<xs:all>
			<xs:element name="host" type="xs:string" />
			<xs:element name="password" type="xs:string" />
			<xs:element name="port" type="xs:int" />
			<xs:element name="protocol" type="xs:string" default="smtp"
				minOccurs="0" />
			<xs:element name="smtpAuth" type="xs:boolean" default="true"
				minOccurs="0" />
			<xs:element name="startTlsEnabled" type="xs:boolean"
				default="true" minOccurs="0" />
			<xs:element name="username" type="xs:string" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="lang">
		<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="country" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="charset" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="order" type="xs:string" use="optional"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="userLog">
		<xs:attribute name="enable" type="xs:boolean"></xs:attribute>
	</xs:complexType>

</xs:schema>

=== simengy/FAE_Link_Analysis/custom_project/xml/apps.xml
<?xml version="1.0" encoding="UTF-8"?>
<apps xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="/schema/app_schema.xsd">
	<app name="vividSenseAppService" root="/custom_project"
		enableUiErrorMsgs="true">
		<datasources>
		
			<datasource name="excelD3Connector"
				class="com.saama.vividsense.datasource.excel.SpreadSheetConnectorFactory">
				<properties>
					<property key="url"
						value="webcontent:/custom_project/xml/workshop/excel/Linklayer.xlsx" />
				</properties>
			</datasource>
		
			<datasource name="excelD3Connector1"
				class="com.saama.vividsense.datasource.excel.SpreadSheetConnectorFactory">
				<properties>
					<property key="url"
						value="webcontent:/custom_project/xml/workshop/excel/Linklayer1.xlsx" />
				</properties>
			</datasource>
			
			<datasource name="excelD3Connector2"
				class="com.saama.vividsense.datasource.excel.SpreadSheetConnectorFactory">
				<properties>
					<property key="url"
						value="webcontent:/custom_project/xml/workshop/excel/Linklayer2.xlsx" />
				</properties>
			</datasource>
			
			
			
		</datasources>
		
		<view>layout.xml</view>

		<!-- Start Email Configuration -->

		<mailConfig>
			<host>smtp.gmail.com</host>
			<password>Your Password</password>
			<port>587</port>
			<protocol>smtp</protocol>
			<smtpAuth>true</smtpAuth>
			<startTlsEnabled>true</startTlsEnabled>
			<username>Your Email Id</username>
		</mailConfig>
		<!-- End Email Configuration -->
	</app>
</apps>

=== simengy/FAE_Link_Analysis/sphinx/xml/apps.xml
<?xml version="1.0" encoding="UTF-8"?>
<apps xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="/schema/app_schema.xsd">
	<app name="sphinx" root="/sphinx" enableUiErrorMsgs="true" >
		<datasources>
			<datasource name="auth"
				class="com.saama.vividsense.datasource.excel.SpreadSheetConnectorFactory">
				<properties>
					<property key="url" value="webcontent:sphinx/xml/demo/auth.xlsx" />
				</properties>
			</datasource>

			<datasource name="excel"
				class="com.saama.vividsense.datasource.excel.SpreadSheetConnectorFactory">
				<properties>
					<property key="url"
						value="webcontent:sphinx/xml/demo/vividsense_13.xlsx" />
				</properties>
			</datasource>

			<datasource name="rdbms"
				class="com.saama.vividsense.datasource.rdbms.HibernateDataSourceFactory">
				<properties>
					<property key="hibernate.connection.driver_class" value="com.mysql.jdbc.Driver"></property>
					<property key="hibernate.connection.url" value="jdbc:mysql://r130:3306/vividsense"></property>
					<property key="hibernate.connection.username" value="root"></property>
					<property key="hibernate.connection.password" value="Saama123"></property>
					<property key="hibernate.dialect" value="org.hibernate.dialect.MySQLDialect"></property>
				</properties>
			</datasource>

			<datasource name="mongo"
				class="com.saama.vividsense.datasource.mongo.MongoDBDatasourceFactory">
				<properties>
					<property key="database_type" value="nosql" />
					<property key="host" value="r131" />
					<property key="port" value="27017" />
					<property key="database.name" value="fifa_wc" />
				</properties>
			</datasource>

		</datasources>
		
		<streams>
			<stream name="test" class="com.saama.vividsense.stream.datasource.DatasourceStreamFactory">
				<properties>
					<property key="datasource" value="rdbms"/>
				</properties>
			</stream>
		</streams>

		<analysises>
			<analysis name="wordCloud"
				class="com.saama.vividsense.analysis.wordcount.WordCloudConnectorFactory">
				<properties>
				</properties>
			</analysis>
		</analysises>
		
		<view>layout.xml</view>
		
		<caches>
			<cache name="guava"
				class="com.saama.vividsense.cache.guava.GuavaCacheManagerFactory">
				<properties>
					<property key="cache_size" value="50" />
					<property key="expire_after_access" value="50" />
				</properties>
			</cache>
			<!-- <cache name="memcache"
				class="com.saama.vividsense.cache.memcache.MemCacheManagerFactory">
				<properties>
					<property key="server" value="r130" />
					<property key="port" value="11211" />
					<property key="expiryTime" value="100000" />
				</properties>
			</cache> -->
		</caches>
		<!-- <messageSource>
			<langs>
				<lang name="dt" country="Dutch" />
				<lang name="fr" country="French" />
				<lang name="en" country="English" />
			</langs>
			<files>
				<file>webcontent:/sphinx/xml/props/dashboard</file>
				<file>webcontent:/sphinx/xml/props/layout</file>
			</files>
		</messageSource>  -->

		<exports>
			<export name="Email" class="com.saama.vividsense.export.EmailExportHandlerFactory"></export>
			<export name="excel" class="com.saama.vividsense.export.excel.ExcelExportHelperFactory"></export>
		</exports>


		<!-- Start Email Configuration -->

		<mailConfig>
			<host>smtp.gmail.com</host>
			<username>userName</username>
			<password>pwd</password>
			<port>587</port>
			<protocol>smtp</protocol>
			<smtpAuth>true</smtpAuth>
			<startTlsEnabled>true</startTlsEnabled>
		</mailConfig>
		<!-- End Email Configuration -->
		
		<!-- <userLog enable="false"/> -->
	</app>
</apps>
